# $File: //ASP/opa/mct/iocs/MCTDEVIOC01/MCTDEVIOC01App/Makefile $
# $Revision: #1 $
# $DateTime: 2022/02/21 12:05:01 $
# Last checked in by: $Author: pozara $
#

TOP = ..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *db*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Db*))
include $(TOP)/configure/RULES_DIRS

# end
